#!/bin/bash

tmux has-session -t cheok 2>/dev/null
if [ $? != 0 ]; then
  tmux new-session -s cheok -n git -d "bash -i"
  tmux split-window -t git
  tmux new-window -n curl -d "bash -i"
  tmux split-window -t curl
  tmux new-window -n cmp -d "bash -i"
  tmux split-window -t cmp
  tmux select-window -t git
fi
tmux attach -t cheok
  
