#!/bin/bash

tmux has-session -t cheok 2>/dev/null
if [ $? != 0 ]; then
  tmux new-session -s cheok -n win1 -d "bash -i"
  tmux new-window -n win2 -d "bash -i"
  tmux new-window -n root -d "bash -i"
  tmux select-window -t win1
fi
tmux attach -t cheok

